Backend updated
nightmare-tech/secure_storage pull request #5
Opened 2024-10-11 04:03 UTC by ritishab0209

Please look into the changes made and merge it

2024-10-11 04:25 UTC, nightmare-tech commented
Please give me an overview of what you've changed/updated/improved.

2024-10-11 05:00 UTC, ritishab0209 commented
Yes, so I have used bcrypt to secure passwords in a better way
Moved the Encryption key to an environment variable for better security
Replaced aes-ecb with aes-cbc for better security
These are the important changes I made, hoping that these changes will get
approved

On Fri, 11 Oct, 2024, 9:55 am Arpit Gupta, ***@***.***> wrote:

> Please give me an overview of what you've changed/updated/improved.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nightmare-tech/secure_storage/pull/5#issuecomment-2406530102>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFUQC5SQZ2DS7HN6MXAEJNLZ25HMVAVCNFSM6AAAAABPYC3BQOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMBWGUZTAMJQGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-11 10:01 UTC, nightmare-tech requested changes
Great!! Here are some things to address:
- include bcrypt in requirements.txt
- other comments in files

2024-10-11 10:01 UTC, nightmare-tech commented on logs/xvba_debug.log
Shouldn't this file be in gitignore?

2024-10-11 10:01 UTC, nightmare-tech commented on app.py
> +encryption_key = os.getenv('ENCRYPTION_KEY', '0123456789abcdef0123456789abcdef').encode()
You should add a warning when the fallback key is used instead of the environment key. This would only happen when the environment variable is not set.

how about this? :
```python
def get_encryption_key():
    key = os.getenv('ENCRYPTION_KEY')
    if key is None:
        print("Warning: Using default encryption key. This is insecure for production use.")
        return b'0123456789abcdef0123456789abcdef'
    return key.encode()

encryption_key = get_encryption_key()
```

2024-10-11 10:01 UTC, nightmare-tech commented on app.py
> +    unpadded_plaintext = unpadder.update(plaintext) + unpadded_plaintext.finalize()
how does this work? isnt  `unpadded_plaintext` not initialised?

2024-10-11 13:09 UTC, ritishab0209 commented
I'll look through it and make all the necessary changes

2024-10-11 16:26 UTC, ritishab0209 commented
Please review it, I have made the said changes

2024-10-11 17:01 UTC, nightmare-tech commented on logs/xvba_debug.log
Put the logs folder in gitignore

2024-10-11 17:05 UTC, nightmare-tech commented
I'm no expert on cryptography but a Google search supports my statement

2024-10-11 17:14 UTC, ritishab0209 commented on logs/xvba_debug.log
Done

2024-10-11 17:29 UTC, ritishab0209 commented
I would say bcrypt is a better option for the safe storage of passwords

On Fri, 11 Oct, 2024, 10:35 pm Arpit Gupta, ***@***.***>
wrote:

> I'm no expert on cryptography but a Google search supports my statement
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nightmare-tech/secure_storage/pull/5#issuecomment-2407810690>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFUQC5XBFE7BIPLXN2ANCM3Z3AAOLAVCNFSM6AAAAABPYC3BQOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMBXHAYTANRZGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-12 14:13 UTC, nightmare-tech approved these changes

2024-10-12 19:38 UTC, merged

2024-10-12 19:42 UTC, nightmare-tech commented
Let me know if this shows up as a contribution in your hacktoberfest account.

2024-10-13 07:21 UTC, ritishab0209 commented
Yes it shows as accepted, thanks

2024-10-16 16:45 UTC, nightmare-tech commented
Solves #4